
// This file has been generated by the GUI designer. Do not modify.
namespace Stetic
{
	internal class Gui
	{
		private static bool initialized;

		internal static void Initialize(Gtk.Widget iconRenderer)
		{
			if ((Stetic.Gui.initialized == false))
			{
				Stetic.Gui.initialized = true;
				global::Gtk.IconFactory w1 = new global::Gtk.IconFactory();
				global::Gtk.IconSet w2 = new global::Gtk.IconSet(global::Gdk.Pixbuf.LoadFromResource("ScapProject0.Icons.icons8-new-window-30.png"));
				w1.Add("add", w2);
				global::Gtk.IconSet w3 = new global::Gtk.IconSet(global::Gdk.Pixbuf.LoadFromResource("ScapProject0.Icons.icons8-delete-24.png"));
				w1.Add("delete", w3);
				global::Gtk.IconSet w4 = new global::Gtk.IconSet(global::Gdk.Pixbuf.LoadFromResource("ScapProject0.Icons.icons8-edit-production-order-32.png"));
				w1.Add("modify", w4);
				global::Gtk.IconSet w5 = new global::Gtk.IconSet(global::Gdk.Pixbuf.LoadFromResource("ScapProject0.Icons.icons8-search-24.png"));
				w1.Add("search", w5);
				global::Gtk.IconSet w6 = new global::Gtk.IconSet(global::Gdk.Pixbuf.LoadFromResource("ScapProject0.Icons.icons8-save-26.png"));
				w1.Add("save", w6);
				global::Gtk.IconSet w7 = new global::Gtk.IconSet(global::Gdk.Pixbuf.LoadFromResource("ScapProject0.Icons.icons8-cancel-50.png"));
				w1.Add("cancel", w7);
				global::Gtk.IconSet w8 = new global::Gtk.IconSet(global::Gdk.Pixbuf.LoadFromResource("ScapProject0.Icons.Custom-Icon-Design-Mono-General-2-Edit.ico"));
				w1.Add("modifywin", w8);
				global::Gtk.IconSet w9 = new global::Gtk.IconSet(global::Gdk.Pixbuf.LoadFromResource("ScapProject0.Icons.Icons8-Windows-8-Files-Add-List.ico"));
				w1.Add("addwin", w9);
				global::Gtk.IconSet w10 = new global::Gtk.IconSet(global::Gdk.Pixbuf.LoadFromResource("ScapProject0.Icons.Iconsmind-Outline-Files.ico"));
				w1.Add("dep", w10);
				global::Gtk.IconSet w11 = new global::Gtk.IconSet(global::Gdk.Pixbuf.LoadFromResource("ScapProject0.Icons.Roundicons-100-Free-Solid-Add-alarm.ico"));
				w1.Add("horarios", w11);
				w1.AddDefault();
			}
		}
	}

	internal class ActionGroups
	{
		public static Gtk.ActionGroup GetActionGroup(System.Type type)
		{
			return Stetic.ActionGroups.GetActionGroup(type.FullName);
		}

		public static Gtk.ActionGroup GetActionGroup(string name)
		{
			return null;
		}
	}
}
