
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0.RegistrosES
{
	public partial class FrmRegistros
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action JustificarAction;

		private global::Gtk.Action BuscarAction;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Toolbar toolbar4;

		private global::Gtk.Label label1;

		private global::Gtk.ComboBoxEntry cbxeEmp;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView trvwRegistros;

		private global::Gtk.Button button1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.RegistrosES.FrmRegistros
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.JustificarAction = new global::Gtk.Action("JustificarAction", global::Mono.Unix.Catalog.GetString("  Justificar"), null, "add");
			this.JustificarAction.IsImportant = true;
			this.JustificarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Justificar");
			w1.Add(this.JustificarAction, null);
			this.BuscarAction = new global::Gtk.Action("BuscarAction", global::Mono.Unix.Catalog.GetString("  Buscar"), null, "search");
			this.BuscarAction.IsImportant = true;
			this.BuscarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Buscar");
			w1.Add(this.BuscarAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ScapProject0.RegistrosES.FrmRegistros";
			this.Title = global::Mono.Unix.Catalog.GetString("Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.RegistrosES.FrmRegistros.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar4\'><toolitem name=\'JustificarAction\' action=\'Justificar" +
					"Action\'/><separator/><toolitem name=\'BuscarAction\' action=\'BuscarAction\'/></tool" +
					"bar></ui>");
			this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar4")));
			this.toolbar4.Name = "toolbar4";
			this.toolbar4.ShowArrow = false;
			this.fixed1.Add(this.toolbar4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.toolbar4]));
			w2.X = 5;
			w2.Y = 5;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w3.X = 27;
			w3.Y = 59;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cbxeEmp = global::Gtk.ComboBoxEntry.NewText();
			this.cbxeEmp.Name = "cbxeEmp";
			this.fixed1.Add(this.cbxeEmp);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cbxeEmp]));
			w4.X = 235;
			w4.Y = 9;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trvwRegistros = new global::Gtk.TreeView();
			this.trvwRegistros.WidthRequest = 715;
			this.trvwRegistros.HeightRequest = 265;
			this.trvwRegistros.CanFocus = true;
			this.trvwRegistros.Name = "trvwRegistros";
			this.GtkScrolledWindow.Add(this.trvwRegistros);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w6.X = 17;
			w6.Y = 103;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed1.Add(this.button1);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
			w7.X = 22;
			w7.Y = 406;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 752;
			this.DefaultHeight = 467;
			this.Show();
			this.JustificarAction.Activated += new global::System.EventHandler(this.OnJustificarActionActivated);
			this.BuscarAction.Activated += new global::System.EventHandler(this.OnBuscarActionActivated);
			this.cbxeEmp.Changed += new global::System.EventHandler(this.OnCbxeEmpChanged);
			this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
		}
	}
}
