
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0.AdminPswd
{
	public partial class FrmModPswd
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action GuardarAction;

		private global::Gtk.Action CancelarAction;

		private global::Gtk.Fixed fixed6;

		private global::Gtk.Button btnBack;

		private global::Gtk.Toolbar toolbar4;

		private global::Gtk.Entry entPwd;

		private global::Gtk.Label label6;

		private global::Gtk.Label label8;

		private global::Gtk.ComboBox cbxUser;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.AdminPswd.FrmModPswd
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.GuardarAction = new global::Gtk.Action("GuardarAction", global::Mono.Unix.Catalog.GetString("  Guardar"), null, "save");
			this.GuardarAction.IsImportant = true;
			this.GuardarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Guardar");
			w1.Add(this.GuardarAction, null);
			this.CancelarAction = new global::Gtk.Action("CancelarAction", global::Mono.Unix.Catalog.GetString("Cancelar"), null, "cancel");
			this.CancelarAction.IsImportant = true;
			this.CancelarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Cancelar");
			w1.Add(this.CancelarAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ScapProject0.AdminPswd.FrmModPswd";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmModPswd");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.AdminPswd.FrmModPswd.Gtk.Container+ContainerChild
			this.fixed6 = new global::Gtk.Fixed();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.btnBack = new global::Gtk.Button();
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed6.Add(this.btnBack);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.btnBack]));
			w2.X = 62;
			w2.Y = 333;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar4\'><toolitem name=\'GuardarAction\' action=\'GuardarAction" +
					"\'/><toolitem name=\'CancelarAction\' action=\'CancelarAction\'/></toolbar></ui>");
			this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar4")));
			this.toolbar4.Name = "toolbar4";
			this.toolbar4.ShowArrow = false;
			this.fixed6.Add(this.toolbar4);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.toolbar4]));
			w3.X = 33;
			w3.Y = 35;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.entPwd = new global::Gtk.Entry();
			this.entPwd.WidthRequest = 200;
			this.entPwd.CanFocus = true;
			this.entPwd.Name = "entPwd";
			this.entPwd.IsEditable = true;
			this.entPwd.InvisibleChar = '•';
			this.fixed6.Add(this.entPwd);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.entPwd]));
			w4.X = 212;
			w4.Y = 244;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario:");
			this.fixed6.Add(this.label6);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.label6]));
			w5.X = 68;
			w5.Y = 152;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Password:");
			this.fixed6.Add(this.label8);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.label8]));
			w6.X = 57;
			w6.Y = 255;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.cbxUser = global::Gtk.ComboBox.NewText();
			this.cbxUser.WidthRequest = 200;
			this.cbxUser.Name = "cbxUser";
			this.fixed6.Add(this.cbxUser);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.cbxUser]));
			w7.X = 209;
			w7.Y = 145;
			this.Add(this.fixed6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 493;
			this.DefaultHeight = 420;
			this.Show();
			this.btnBack.Clicked += new global::System.EventHandler(this.OnBtnBackClicked);
		}
	}
}
