
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0
{
	public partial class FrmLoginEmpleado
	{
		private global::Gtk.Fixed fixed5;

		private global::Gtk.Label label7;

		private global::Gtk.ComboBox combobox7;

		private global::Gtk.Label label8;

		private global::Gtk.ComboBox combobox8;

		private global::Gtk.Button button13;

		private global::Gtk.Button button14;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.FrmLoginEmpleado
			this.Name = "ScapProject0.FrmLoginEmpleado";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmLoginEmpleado");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.FrmLoginEmpleado.Gtk.Container+ContainerChild
			this.fixed5 = new global::Gtk.Fixed();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Empleado:");
			this.fixed5.Add(this.label7);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label7]));
			w1.X = 88;
			w1.Y = 48;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.combobox7 = global::Gtk.ComboBox.NewText();
			this.combobox7.WidthRequest = 220;
			this.combobox7.HeightRequest = 25;
			this.combobox7.Name = "combobox7";
			this.fixed5.Add(this.combobox7);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.combobox7]));
			w2.X = 88;
			w2.Y = 80;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("PIN:");
			this.fixed5.Add(this.label8);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label8]));
			w3.X = 88;
			w3.Y = 142;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.combobox8 = global::Gtk.ComboBox.NewText();
			this.combobox8.WidthRequest = 220;
			this.combobox8.HeightRequest = 25;
			this.combobox8.Name = "combobox8";
			this.fixed5.Add(this.combobox8);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.combobox8]));
			w4.X = 88;
			w4.Y = 174;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.button13 = new global::Gtk.Button();
			this.button13.WidthRequest = 119;
			this.button13.HeightRequest = 25;
			this.button13.CanFocus = true;
			this.button13.Name = "button13";
			this.button13.UseUnderline = true;
			this.button13.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.fixed5.Add(this.button13);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.button13]));
			w5.X = 44;
			w5.Y = 239;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.button14 = new global::Gtk.Button();
			this.button14.WidthRequest = 119;
			this.button14.HeightRequest = 25;
			this.button14.CanFocus = true;
			this.button14.Name = "button14";
			this.button14.UseUnderline = true;
			this.button14.Label = global::Mono.Unix.Catalog.GetString("Ingresar");
			this.fixed5.Add(this.button14);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.button14]));
			w6.X = 235;
			w6.Y = 239;
			this.Add(this.fixed5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.button14.Clicked += new global::System.EventHandler(this.OnButton14Clicked);
		}
	}
}
