
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0.Horarios
{
	public partial class FrmAddHor
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action saveAction;

		private global::Gtk.Action cancelAction;

		private global::Gtk.Action GuardarAction;

		private global::Gtk.Action cancelAction1;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Entry entNombreHor;

		private global::Gtk.Toolbar toolbar3;

		private global::Gtk.Button btnRegresarAddHor;

		private global::Gtk.Entry entHoraFin;

		private global::Gtk.Entry entAlmuerzo;

		private global::Gtk.Entry entHoraIn;

		private global::Gtk.Label label5;

		private global::Gtk.Label label1;

		private global::Gtk.Label label4;

		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.Horarios.FrmAddHor
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.saveAction = new global::Gtk.Action("saveAction", null, null, "save");
			w1.Add(this.saveAction, null);
			this.cancelAction = new global::Gtk.Action("cancelAction", null, null, "cancel");
			w1.Add(this.cancelAction, null);
			this.GuardarAction = new global::Gtk.Action("GuardarAction", global::Mono.Unix.Catalog.GetString("  Guardar"), null, "save");
			this.GuardarAction.IsImportant = true;
			this.GuardarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Guardar");
			w1.Add(this.GuardarAction, null);
			this.cancelAction1 = new global::Gtk.Action("cancelAction1", null, null, "cancel");
			this.cancelAction1.IsImportant = true;
			this.cancelAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("  Cancelar");
			w1.Add(this.cancelAction1, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ScapProject0.Horarios.FrmAddHor";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmAddHor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.Horarios.FrmAddHor.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entNombreHor = new global::Gtk.Entry();
			this.entNombreHor.CanFocus = true;
			this.entNombreHor.Name = "entNombreHor";
			this.entNombreHor.IsEditable = true;
			this.entNombreHor.InvisibleChar = '•';
			this.fixed2.Add(this.entNombreHor);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entNombreHor]));
			w2.X = 192;
			w2.Y = 84;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar3\'><toolitem name=\'GuardarAction\' action=\'GuardarAction" +
					"\'/><toolitem name=\'cancelAction1\' action=\'cancelAction1\'/></toolbar></ui>");
			this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar3")));
			this.toolbar3.Name = "toolbar3";
			this.toolbar3.ShowArrow = false;
			this.fixed2.Add(this.toolbar3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.toolbar3]));
			w3.X = -2;
			w3.Y = 11;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnRegresarAddHor = new global::Gtk.Button();
			this.btnRegresarAddHor.CanFocus = true;
			this.btnRegresarAddHor.Name = "btnRegresarAddHor";
			this.btnRegresarAddHor.UseUnderline = true;
			this.btnRegresarAddHor.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed2.Add(this.btnRegresarAddHor);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnRegresarAddHor]));
			w4.X = 29;
			w4.Y = 297;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entHoraFin = new global::Gtk.Entry();
			this.entHoraFin.CanFocus = true;
			this.entHoraFin.Name = "entHoraFin";
			this.entHoraFin.IsEditable = true;
			this.entHoraFin.InvisibleChar = '•';
			this.fixed2.Add(this.entHoraFin);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entHoraFin]));
			w5.X = 192;
			w5.Y = 177;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entAlmuerzo = new global::Gtk.Entry();
			this.entAlmuerzo.CanFocus = true;
			this.entAlmuerzo.Name = "entAlmuerzo";
			this.entAlmuerzo.IsEditable = true;
			this.entAlmuerzo.InvisibleChar = '•';
			this.fixed2.Add(this.entAlmuerzo);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entAlmuerzo]));
			w6.X = 192;
			w6.Y = 223;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entHoraIn = new global::Gtk.Entry();
			this.entHoraIn.CanFocus = true;
			this.entHoraIn.Name = "entHoraIn";
			this.entHoraIn.IsEditable = true;
			this.entHoraIn.InvisibleChar = '•';
			this.fixed2.Add(this.entHoraIn);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entHoraIn]));
			w7.X = 192;
			w7.Y = 129;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Hora de fin:");
			this.fixed2.Add(this.label5);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label5]));
			w8.X = 75;
			w8.Y = 190;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Tiempo de almuerzo:");
			this.fixed2.Add(this.label1);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label1]));
			w9.X = 14;
			w9.Y = 230;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Hora de inicio:");
			this.fixed2.Add(this.label4);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label4]));
			w10.X = 56;
			w10.Y = 138;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
			this.fixed2.Add(this.label3);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label3]));
			w11.X = 92;
			w11.Y = 91;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 452;
			this.DefaultHeight = 355;
			this.Show();
			this.GuardarAction.Activated += new global::System.EventHandler(this.OnGuardarActionActivated);
			this.btnRegresarAddHor.Clicked += new global::System.EventHandler(this.OnBtnRegresarAddHorClicked);
		}
	}
}
