
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0.Roles
{
	public partial class FrmModRol
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action btnGuardar;

		private global::Gtk.Action btnCancelar;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Button btnRegresar;

		private global::Gtk.Entry txtID;

		private global::Gtk.Entry txtRol;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView trvwRolOpcion;

		private global::Gtk.Label label4;

		private global::Gtk.ComboBox cbxOpcion;

		private global::Gtk.Button btnAgregar;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.Toolbar toolbar2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.Roles.FrmModRol
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.btnGuardar = new global::Gtk.Action("btnGuardar", global::Mono.Unix.Catalog.GetString("  Guardar"), null, "save");
			this.btnGuardar.IsImportant = true;
			this.btnGuardar.ShortLabel = global::Mono.Unix.Catalog.GetString("  Guardar");
			w1.Add(this.btnGuardar, null);
			this.btnCancelar = new global::Gtk.Action("btnCancelar", global::Mono.Unix.Catalog.GetString("  Cancelar"), null, "cancel");
			this.btnCancelar.IsImportant = true;
			this.btnCancelar.ShortLabel = global::Mono.Unix.Catalog.GetString("  Cancelar");
			w1.Add(this.btnCancelar, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ScapProject0.Roles.FrmModRol";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmModRol");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ScapProject0.Roles.FrmModRol.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnRegresar = new global::Gtk.Button();
			this.btnRegresar.CanFocus = true;
			this.btnRegresar.Name = "btnRegresar";
			this.btnRegresar.UseUnderline = true;
			this.btnRegresar.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed1.Add(this.btnRegresar);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnRegresar]));
			w2.X = 26;
			w2.Y = 365;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtID = new global::Gtk.Entry();
			this.txtID.Name = "txtID";
			this.txtID.IsEditable = false;
			this.txtID.InvisibleChar = '•';
			this.fixed1.Add(this.txtID);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtID]));
			w3.X = 120;
			w3.Y = 81;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtRol = new global::Gtk.Entry();
			this.txtRol.CanFocus = true;
			this.txtRol.Name = "txtRol";
			this.txtRol.IsEditable = true;
			this.txtRol.InvisibleChar = '•';
			this.fixed1.Add(this.txtRol);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtRol]));
			w4.X = 120;
			w4.Y = 141;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("ID: ");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w5.X = 79;
			w5.Y = 88;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Rol:");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w6.X = 73;
			w6.Y = 150;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 180;
			this.GtkScrolledWindow.HeightRequest = 240;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trvwRolOpcion = new global::Gtk.TreeView();
			this.trvwRolOpcion.CanFocus = true;
			this.trvwRolOpcion.Name = "trvwRolOpcion";
			this.GtkScrolledWindow.Add(this.trvwRolOpcion);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w8.X = 350;
			w8.Y = 81;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Opcion:");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w9.X = 47;
			w9.Y = 207;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cbxOpcion = global::Gtk.ComboBox.NewText();
			this.cbxOpcion.WidthRequest = 172;
			this.cbxOpcion.Name = "cbxOpcion";
			this.fixed1.Add(this.cbxOpcion);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cbxOpcion]));
			w10.X = 120;
			w10.Y = 199;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnAgregar = new global::Gtk.Button();
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.fixed1.Add(this.btnAgregar);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnAgregar]));
			w11.X = 120;
			w11.Y = 240;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed1.Add(this.btnEliminar);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnEliminar]));
			w12.X = 218;
			w12.Y = 240;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar2\'><toolitem name=\'btnGuardar\' action=\'btnGuardar\'/><to" +
					"olitem name=\'btnCancelar\' action=\'btnCancelar\'/></toolbar></ui>");
			this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar2")));
			this.toolbar2.Name = "toolbar2";
			this.toolbar2.ShowArrow = false;
			this.fixed1.Add(this.toolbar2);
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 595;
			this.DefaultHeight = 453;
			this.Show();
			this.btnGuardar.Activated += new global::System.EventHandler(this.OnBtnGuardarActivated);
			this.btnCancelar.Activated += new global::System.EventHandler(this.OnBtnCancelarActivated);
			this.btnRegresar.Clicked += new global::System.EventHandler(this.OnBtnRegresarClicked);
			this.btnAgregar.Clicked += new global::System.EventHandler(this.OnBtnAgregarClicked);
		}
	}
}
