
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0.Empleados
{
	public partial class FrmModEmp
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action GuardarAction;

		private global::Gtk.Action CancelarAction;

		private global::Gtk.Action searchAction;

		private global::Gtk.Action GuardarAction1;

		private global::Gtk.Action CancelarAction1;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Label label9;

		private global::Gtk.Label label10;

		private global::Gtk.Label label11;

		private global::Gtk.Label label12;

		private global::Gtk.Label label13;

		private global::Gtk.Label label14;

		private global::Gtk.Label label15;

		private global::Gtk.Label label16;

		private global::Gtk.Entry entId;

		private global::Gtk.Entry entNombres;

		private global::Gtk.Entry entApellidos;

		private global::Gtk.Entry entCedula;

		private global::Gtk.ComboBoxEntry cbxDpto;

		private global::Gtk.ComboBoxEntry cbxCargo;

		private global::Gtk.Entry entTel;

		private global::Gtk.Entry entEmail;

		private global::Gtk.Button button3;

		private global::Gtk.Toolbar toolbar3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.Empleados.FrmModEmp
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.GuardarAction = new global::Gtk.Action("GuardarAction", global::Mono.Unix.Catalog.GetString("  Guardar"), null, "save");
			this.GuardarAction.IsImportant = true;
			this.GuardarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Guardar");
			w1.Add(this.GuardarAction, null);
			this.CancelarAction = new global::Gtk.Action("CancelarAction", global::Mono.Unix.Catalog.GetString("  Cancelar"), null, "cancel");
			this.CancelarAction.IsImportant = true;
			this.CancelarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Cancelar");
			w1.Add(this.CancelarAction, null);
			this.searchAction = new global::Gtk.Action("searchAction", null, null, "search");
			w1.Add(this.searchAction, null);
			this.GuardarAction1 = new global::Gtk.Action("GuardarAction1", global::Mono.Unix.Catalog.GetString("  Guardar"), null, "save");
			this.GuardarAction1.IsImportant = true;
			this.GuardarAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("  Guardar");
			w1.Add(this.GuardarAction1, null);
			this.CancelarAction1 = new global::Gtk.Action("CancelarAction1", global::Mono.Unix.Catalog.GetString("  Cancelar"), null, "cancel");
			this.CancelarAction1.IsImportant = true;
			this.CancelarAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("  Cancelar");
			w1.Add(this.CancelarAction1, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ScapProject0.Empleados.FrmModEmp";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmModEmp");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.Empleados.FrmModEmp.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("ID:");
			this.fixed4.Add(this.label9);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label9]));
			w2.X = 25;
			w2.Y = 80;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Nombres:");
			this.fixed4.Add(this.label10);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label10]));
			w3.X = 25;
			w3.Y = 120;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Apellidos:");
			this.fixed4.Add(this.label11);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label11]));
			w4.X = 25;
			w4.Y = 160;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Cedula:");
			this.fixed4.Add(this.label12);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label12]));
			w5.X = 25;
			w5.Y = 200;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Departamento:");
			this.fixed4.Add(this.label13);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label13]));
			w6.X = 25;
			w6.Y = 240;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Cargo:");
			this.fixed4.Add(this.label14);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label14]));
			w7.X = 25;
			w7.Y = 280;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Telefono:");
			this.fixed4.Add(this.label15);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label15]));
			w8.X = 25;
			w8.Y = 320;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Email:");
			this.fixed4.Add(this.label16);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label16]));
			w9.X = 25;
			w9.Y = 360;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.entId = new global::Gtk.Entry();
			this.entId.CanFocus = true;
			this.entId.Name = "entId";
			this.entId.IsEditable = true;
			this.entId.InvisibleChar = '•';
			this.fixed4.Add(this.entId);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.entId]));
			w10.X = 160;
			w10.Y = 70;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.entNombres = new global::Gtk.Entry();
			this.entNombres.CanFocus = true;
			this.entNombres.Name = "entNombres";
			this.entNombres.IsEditable = true;
			this.entNombres.InvisibleChar = '•';
			this.fixed4.Add(this.entNombres);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.entNombres]));
			w11.X = 160;
			w11.Y = 110;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.entApellidos = new global::Gtk.Entry();
			this.entApellidos.CanFocus = true;
			this.entApellidos.Name = "entApellidos";
			this.entApellidos.IsEditable = true;
			this.entApellidos.InvisibleChar = '•';
			this.fixed4.Add(this.entApellidos);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.entApellidos]));
			w12.X = 160;
			w12.Y = 150;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.entCedula = new global::Gtk.Entry();
			this.entCedula.CanFocus = true;
			this.entCedula.Name = "entCedula";
			this.entCedula.IsEditable = true;
			this.entCedula.InvisibleChar = '•';
			this.fixed4.Add(this.entCedula);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.entCedula]));
			w13.X = 160;
			w13.Y = 190;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.cbxDpto = global::Gtk.ComboBoxEntry.NewText();
			this.cbxDpto.WidthRequest = 172;
			this.cbxDpto.Name = "cbxDpto";
			this.fixed4.Add(this.cbxDpto);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.cbxDpto]));
			w14.X = 160;
			w14.Y = 230;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.cbxCargo = global::Gtk.ComboBoxEntry.NewText();
			this.cbxCargo.WidthRequest = 172;
			this.cbxCargo.Name = "cbxCargo";
			this.fixed4.Add(this.cbxCargo);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.cbxCargo]));
			w15.X = 160;
			w15.Y = 270;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.entTel = new global::Gtk.Entry();
			this.entTel.CanFocus = true;
			this.entTel.Name = "entTel";
			this.entTel.IsEditable = true;
			this.entTel.InvisibleChar = '•';
			this.fixed4.Add(this.entTel);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.entTel]));
			w16.X = 160;
			w16.Y = 310;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.entEmail = new global::Gtk.Entry();
			this.entEmail.CanFocus = true;
			this.entEmail.Name = "entEmail";
			this.entEmail.IsEditable = true;
			this.entEmail.InvisibleChar = '•';
			this.fixed4.Add(this.entEmail);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.entEmail]));
			w17.X = 160;
			w17.Y = 350;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed4.Add(this.button3);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.button3]));
			w18.X = 13;
			w18.Y = 425;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar3\'><toolitem name=\'GuardarAction1\' action=\'GuardarActio" +
					"n1\'/><separator/><toolitem name=\'CancelarAction1\' action=\'CancelarAction1\'/></to" +
					"olbar></ui>");
			this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar3")));
			this.toolbar3.Name = "toolbar3";
			this.toolbar3.ShowArrow = false;
			this.fixed4.Add(this.toolbar3);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.toolbar3]));
			w19.X = 3;
			w19.Y = 7;
			this.Add(this.fixed4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 409;
			this.DefaultHeight = 483;
			this.Show();
			this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		}
	}
}
