
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0.UserRol
{
	public partial class frmAddUserRol
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.UserRol.frmAddUserRol
			this.Name = "ScapProject0.UserRol.frmAddUserRol";
			this.Title = global::Mono.Unix.Catalog.GetString("frmAddUserRol");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
