
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0.Departamentos
{
	public partial class FrmAddDpto
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action GuardarAction;

		private global::Gtk.Action cancelAction;

		private global::Gtk.Action CancelarAction;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.Toolbar toolbar2;

		private global::Gtk.Button btnBackAddDpto;

		private global::Gtk.Label label3;

		private global::Gtk.Entry txtNombre;

		private global::Gtk.Entry txtExt;

		private global::Gtk.Entry txtEmail;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.Departamentos.FrmAddDpto
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.GuardarAction = new global::Gtk.Action("GuardarAction", global::Mono.Unix.Catalog.GetString("  Guardar"), null, "save");
			this.GuardarAction.IsImportant = true;
			this.GuardarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Guardar");
			w1.Add(this.GuardarAction, null);
			this.cancelAction = new global::Gtk.Action("cancelAction", null, null, "cancel");
			w1.Add(this.cancelAction, null);
			this.CancelarAction = new global::Gtk.Action("CancelarAction", global::Mono.Unix.Catalog.GetString("  Cancelar"), null, "cancel");
			this.CancelarAction.IsImportant = true;
			this.CancelarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Cancelar");
			w1.Add(this.CancelarAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ScapProject0.Departamentos.FrmAddDpto";
			this.Title = global::Mono.Unix.Catalog.GetString("Agregar departamento");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.Departamentos.FrmAddDpto.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar2\'><toolitem name=\'GuardarAction\' action=\'GuardarAction" +
					"\'/><separator/><toolitem name=\'CancelarAction\' action=\'CancelarAction\'/></toolba" +
					"r></ui>");
			this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar2")));
			this.toolbar2.Name = "toolbar2";
			this.toolbar2.ShowArrow = false;
			this.fixed3.Add(this.toolbar2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.toolbar2]));
			w2.X = 25;
			w2.Y = 15;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btnBackAddDpto = new global::Gtk.Button();
			this.btnBackAddDpto.CanFocus = true;
			this.btnBackAddDpto.Name = "btnBackAddDpto";
			this.btnBackAddDpto.UseUnderline = true;
			this.btnBackAddDpto.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed3.Add(this.btnBackAddDpto);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btnBackAddDpto]));
			w3.X = 40;
			w3.Y = 226;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
			this.fixed3.Add(this.label3);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label3]));
			w4.X = 81;
			w4.Y = 83;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.txtNombre = new global::Gtk.Entry();
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '•';
			this.fixed3.Add(this.txtNombre);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txtNombre]));
			w5.X = 159;
			w5.Y = 73;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.txtExt = new global::Gtk.Entry();
			this.txtExt.CanFocus = true;
			this.txtExt.Name = "txtExt";
			this.txtExt.IsEditable = true;
			this.txtExt.InvisibleChar = '•';
			this.fixed3.Add(this.txtExt);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txtExt]));
			w6.X = 160;
			w6.Y = 123;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.txtEmail = new global::Gtk.Entry();
			this.txtEmail.CanFocus = true;
			this.txtEmail.Name = "txtEmail";
			this.txtEmail.IsEditable = true;
			this.txtEmail.InvisibleChar = '•';
			this.fixed3.Add(this.txtEmail);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txtEmail]));
			w7.X = 161;
			w7.Y = 174;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Extensión:");
			this.fixed3.Add(this.label1);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label1]));
			w8.X = 77;
			w8.Y = 129;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Email:");
			this.fixed3.Add(this.label2);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label2]));
			w9.X = 106;
			w9.Y = 180;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 465;
			this.DefaultHeight = 300;
			this.Show();
			this.GuardarAction.Activated += new global::System.EventHandler(this.OnGuardarActionActivated);
			this.btnBackAddDpto.Clicked += new global::System.EventHandler(this.OnBtnBackAddDptoClicked);
		}
	}
}
