
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0
{
	public partial class FrmMenuAdmin
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action Configuracion;

		private global::Gtk.Action Action;

		private global::Gtk.Fixed fixed9;

		private global::Gtk.Button button22;

		private global::Gtk.Button button25;

		private global::Gtk.Button button24;

		private global::Gtk.Button button23;

		private global::Gtk.Toolbar toolbar1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.FrmMenuAdmin
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.Configuracion = new global::Gtk.Action("Configuracion", global::Mono.Unix.Catalog.GetString("Configuracion"), null, "modify");
			this.Configuracion.ShortLabel = global::Mono.Unix.Catalog.GetString("Configuracion");
			w1.Add(this.Configuracion, null);
			this.Action = new global::Gtk.Action("Action", null, null, null);
			w1.Add(this.Action, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ScapProject0.FrmMenuAdmin";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmMenuAdmin");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.FrmMenuAdmin.Gtk.Container+ContainerChild
			this.fixed9 = new global::Gtk.Fixed();
			this.fixed9.Name = "fixed9";
			this.fixed9.HasWindow = false;
			// Container child fixed9.Gtk.Fixed+FixedChild
			this.button22 = new global::Gtk.Button();
			this.button22.WidthRequest = 221;
			this.button22.HeightRequest = 29;
			this.button22.CanFocus = true;
			this.button22.Name = "button22";
			this.button22.UseUnderline = true;
			this.button22.Label = global::Mono.Unix.Catalog.GetString("EMPLEADOS");
			this.fixed9.Add(this.button22);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed9[this.button22]));
			w2.X = 90;
			w2.Y = 45;
			// Container child fixed9.Gtk.Fixed+FixedChild
			this.button25 = new global::Gtk.Button();
			this.button25.WidthRequest = 119;
			this.button25.HeightRequest = 25;
			this.button25.CanFocus = true;
			this.button25.Name = "button25";
			this.button25.UseUnderline = true;
			this.button25.Label = global::Mono.Unix.Catalog.GetString("REGRESAR");
			this.fixed9.Add(this.button25);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed9[this.button25]));
			w3.X = 15;
			w3.Y = 260;
			// Container child fixed9.Gtk.Fixed+FixedChild
			this.button24 = new global::Gtk.Button();
			this.button24.WidthRequest = 221;
			this.button24.HeightRequest = 29;
			this.button24.CanFocus = true;
			this.button24.Name = "button24";
			this.button24.UseUnderline = true;
			this.button24.Label = global::Mono.Unix.Catalog.GetString("GENERAR REPORTES");
			this.fixed9.Add(this.button24);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed9[this.button24]));
			w4.X = 90;
			w4.Y = 191;
			// Container child fixed9.Gtk.Fixed+FixedChild
			this.button23 = new global::Gtk.Button();
			this.button23.WidthRequest = 221;
			this.button23.HeightRequest = 29;
			this.button23.CanFocus = true;
			this.button23.Name = "button23";
			this.button23.UseUnderline = true;
			this.button23.Label = global::Mono.Unix.Catalog.GetString("REGISTROS");
			this.fixed9.Add(this.button23);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed9[this.button23]));
			w5.X = 90;
			w5.Y = 118;
			// Container child fixed9.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar1\'><toolitem name=\'Configuracion\' action=\'Configuracion" +
					"\'/><separator/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.fixed9.Add(this.toolbar1);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed9[this.toolbar1]));
			w6.X = 2;
			w6.Y = 4;
			this.Add(this.fixed9);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.Configuracion.Activated += new global::System.EventHandler(this.OnConfiguracionActivated);
			this.button22.Clicked += new global::System.EventHandler(this.OnButton22Clicked);
			this.button25.Clicked += new global::System.EventHandler(this.OnButton25Clicked);
			this.button24.Clicked += new global::System.EventHandler(this.OnButton24Clicked);
			this.button23.Clicked += new global::System.EventHandler(this.OnButton23Clicked);
		}
	}
}
