
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0.AdminPswd
{
	public partial class FrmAddPswd
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action GuardarAction;

		private global::Gtk.Action CancelarAction;

		private global::Gtk.Fixed fixed5;

		private global::Gtk.Button btnBack;

		private global::Gtk.Toolbar toolbar6;

		private global::Gtk.Entry entPwd;

		private global::Gtk.Label label4;

		private global::Gtk.Label label2;

		private global::Gtk.ComboBox cbxUser;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.AdminPswd.FrmAddPswd
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.GuardarAction = new global::Gtk.Action("GuardarAction", global::Mono.Unix.Catalog.GetString("  Guardar"), null, "save");
			this.GuardarAction.IsImportant = true;
			this.GuardarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Guardar");
			w1.Add(this.GuardarAction, null);
			this.CancelarAction = new global::Gtk.Action("CancelarAction", global::Mono.Unix.Catalog.GetString("  Cancelar"), null, "cancel");
			this.CancelarAction.IsImportant = true;
			this.CancelarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Cancelar");
			w1.Add(this.CancelarAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ScapProject0.AdminPswd.FrmAddPswd";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmAddPswd");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.AdminPswd.FrmAddPswd.Gtk.Container+ContainerChild
			this.fixed5 = new global::Gtk.Fixed();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.btnBack = new global::Gtk.Button();
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed5.Add(this.btnBack);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.btnBack]));
			w2.X = 62;
			w2.Y = 332;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar6\'><toolitem name=\'GuardarAction\' action=\'GuardarAction" +
					"\'/><toolitem name=\'CancelarAction\' action=\'CancelarAction\'/></toolbar></ui>");
			this.toolbar6 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar6")));
			this.toolbar6.Name = "toolbar6";
			this.toolbar6.ShowArrow = false;
			this.fixed5.Add(this.toolbar6);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.toolbar6]));
			w3.X = 20;
			w3.Y = 9;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entPwd = new global::Gtk.Entry();
			this.entPwd.WidthRequest = 200;
			this.entPwd.CanFocus = true;
			this.entPwd.Name = "entPwd";
			this.entPwd.IsEditable = true;
			this.entPwd.InvisibleChar = '•';
			this.fixed5.Add(this.entPwd);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entPwd]));
			w4.X = 230;
			w4.Y = 248;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("New password:");
			this.fixed5.Add(this.label4);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label4]));
			w5.X = 59;
			w5.Y = 255;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario:");
			this.fixed5.Add(this.label2);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label2]));
			w6.X = 71;
			w6.Y = 141;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.cbxUser = global::Gtk.ComboBox.NewText();
			this.cbxUser.WidthRequest = 200;
			this.cbxUser.Name = "cbxUser";
			this.fixed5.Add(this.cbxUser);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.cbxUser]));
			w7.X = 226;
			w7.Y = 134;
			this.Add(this.fixed5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 535;
			this.DefaultHeight = 414;
			this.Show();
			this.btnBack.Clicked += new global::System.EventHandler(this.OnBtnBackClicked);
		}
	}
}
