
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0.AdminPswd
{
	public partial class FrmAdminPswd
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action AgregarAction;

		private global::Gtk.Action r;

		private global::Gtk.Action EliminarAction;

		private global::Gtk.Action ModificarAction;

		private global::Gtk.Action BuscarAction;

		private global::Gtk.Action CancelarAction;

		private global::Gtk.Action ModificarAction1;

		private global::Gtk.Action BuscarAction1;

		private global::Gtk.Action AgregarAction1;

		private global::Gtk.Action EliminarAction1;

		private global::Gtk.Action ModificarAction2;

		private global::Gtk.Action BuscarAction2;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Button btnBack;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.Entry entry4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView trvwAdminPswd;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.AdminPswd.FrmAdminPswd
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.AgregarAction = new global::Gtk.Action("AgregarAction", global::Mono.Unix.Catalog.GetString("  Agregar "), null, "add");
			this.AgregarAction.IsImportant = true;
			this.AgregarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Agregar");
			w1.Add(this.AgregarAction, null);
			this.r = new global::Gtk.Action("r", global::Mono.Unix.Catalog.GetString("Eliminar"), null, "gtk-redo");
			this.r.IsImportant = true;
			this.r.ShortLabel = global::Mono.Unix.Catalog.GetString("Eliminar");
			w1.Add(this.r, null);
			this.EliminarAction = new global::Gtk.Action("EliminarAction", global::Mono.Unix.Catalog.GetString("  Eliminar"), null, "delete");
			this.EliminarAction.HideIfEmpty = false;
			this.EliminarAction.IsImportant = true;
			this.EliminarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Eliminar");
			w1.Add(this.EliminarAction, null);
			this.ModificarAction = new global::Gtk.Action("ModificarAction", global::Mono.Unix.Catalog.GetString("  Modificar"), null, "modify");
			this.ModificarAction.HideIfEmpty = false;
			this.ModificarAction.IsImportant = true;
			this.ModificarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Modificar");
			w1.Add(this.ModificarAction, null);
			this.BuscarAction = new global::Gtk.Action("BuscarAction", global::Mono.Unix.Catalog.GetString("  Buscar"), null, "search");
			this.BuscarAction.HideIfEmpty = false;
			this.BuscarAction.IsImportant = true;
			this.BuscarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Buscar");
			w1.Add(this.BuscarAction, null);
			this.CancelarAction = new global::Gtk.Action("CancelarAction", global::Mono.Unix.Catalog.GetString("  Cancelar "), null, "delete");
			this.CancelarAction.HideIfEmpty = false;
			this.CancelarAction.IsImportant = true;
			this.CancelarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Cancelar");
			w1.Add(this.CancelarAction, null);
			this.ModificarAction1 = new global::Gtk.Action("ModificarAction1", global::Mono.Unix.Catalog.GetString("  Modificar"), null, "modify");
			this.ModificarAction1.IsImportant = true;
			this.ModificarAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("  Modificar");
			w1.Add(this.ModificarAction1, null);
			this.BuscarAction1 = new global::Gtk.Action("BuscarAction1", global::Mono.Unix.Catalog.GetString("  Buscar"), null, "search");
			this.BuscarAction1.IsImportant = true;
			this.BuscarAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("  Buscar");
			w1.Add(this.BuscarAction1, null);
			this.AgregarAction1 = new global::Gtk.Action("AgregarAction1", global::Mono.Unix.Catalog.GetString("  Agregar"), null, "add");
			this.AgregarAction1.IsImportant = true;
			this.AgregarAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("  Agregar");
			w1.Add(this.AgregarAction1, null);
			this.EliminarAction1 = new global::Gtk.Action("EliminarAction1", global::Mono.Unix.Catalog.GetString("  Eliminar"), null, "delete");
			this.EliminarAction1.IsImportant = true;
			this.EliminarAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("  Eliminar");
			w1.Add(this.EliminarAction1, null);
			this.ModificarAction2 = new global::Gtk.Action("ModificarAction2", global::Mono.Unix.Catalog.GetString("  Modificar"), null, "modify");
			this.ModificarAction2.IsImportant = true;
			this.ModificarAction2.ShortLabel = global::Mono.Unix.Catalog.GetString("  Modificar");
			w1.Add(this.ModificarAction2, null);
			this.BuscarAction2 = new global::Gtk.Action("BuscarAction2", global::Mono.Unix.Catalog.GetString("  Buscar"), null, "search");
			this.BuscarAction2.IsImportant = true;
			this.BuscarAction2.ShortLabel = global::Mono.Unix.Catalog.GetString("  Buscar");
			w1.Add(this.BuscarAction2, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ScapProject0.AdminPswd.FrmAdminPswd";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmAdminPswd");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.AdminPswd.FrmAdminPswd.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.btnBack = new global::Gtk.Button();
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed4.Add(this.btnBack);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.btnBack]));
			w2.X = 43;
			w2.Y = 380;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString(@"<ui><toolbar name='toolbar1'><toolitem name='AgregarAction1' action='AgregarAction1'/><toolitem name='EliminarAction1' action='EliminarAction1'/><toolitem name='ModificarAction2' action='ModificarAction2'/><toolitem name='BuscarAction2' action='BuscarAction2'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.fixed4.Add(this.toolbar1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.toolbar1]));
			w3.X = -2;
			w3.Y = 8;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.entry4 = new global::Gtk.Entry();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '•';
			this.fixed4.Add(this.entry4);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.entry4]));
			w4.X = 419;
			w4.Y = 13;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 620;
			this.GtkScrolledWindow.HeightRequest = 280;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trvwAdminPswd = new global::Gtk.TreeView();
			this.trvwAdminPswd.WidthRequest = 500;
			this.trvwAdminPswd.HeightRequest = 200;
			this.trvwAdminPswd.CanFocus = true;
			this.trvwAdminPswd.Name = "trvwAdminPswd";
			this.GtkScrolledWindow.Add(this.trvwAdminPswd);
			this.fixed4.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.GtkScrolledWindow]));
			w6.X = 16;
			w6.Y = 81;
			this.Add(this.fixed4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 659;
			this.DefaultHeight = 438;
			this.Show();
			//this.AgregarAction.Activated += new global::System.EventHandler(this.OnAgregarActionActivated);
			this.AgregarAction1.Activated += new global::System.EventHandler(this.OnAddActionActivated);
			this.EliminarAction1.Activated += new global::System.EventHandler(this.OnEliminarAction1Activated);
			this.ModificarAction2.Activated += new global::System.EventHandler(this.OnModificarAction2Activated);
			this.btnBack.Clicked += new global::System.EventHandler(this.OnBtnBackClicked);
			this.trvwAdminPswd.CursorChanged += new global::System.EventHandler(this.OnTrvwAdminPswdCursorChanged);
			this.trvwAdminPswd.RowActivated += new global::Gtk.RowActivatedHandler(this.OnTrvwAdminPswdRowActivated);
		}
	}
}
