
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0.Opcion
{
	public partial class FrmAddOpc
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action btnSave;

		private global::Gtk.Action btnCancel;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.Toolbar toolbar4;

		private global::Gtk.Label label4;

		private global::Gtk.Entry txtOpc;

		private global::Gtk.Button btnBack;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.Opcion.FrmAddOpc
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.btnSave = new global::Gtk.Action("btnSave", global::Mono.Unix.Catalog.GetString("Guardar"), null, "save");
			this.btnSave.IsImportant = true;
			this.btnSave.ShortLabel = global::Mono.Unix.Catalog.GetString("Guardar");
			w1.Add(this.btnSave, null);
			this.btnCancel = new global::Gtk.Action("btnCancel", global::Mono.Unix.Catalog.GetString("Cancelar"), null, "cancel");
			this.btnCancel.IsImportant = true;
			this.btnCancel.ShortLabel = global::Mono.Unix.Catalog.GetString("Cancelar");
			w1.Add(this.btnCancel, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ScapProject0.Opcion.FrmAddOpc";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmAddOpc");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ScapProject0.Opcion.FrmAddOpc.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar4\'><toolitem name=\'btnSave\' action=\'btnSave\'/><toolitem" +
					" name=\'btnCancel\' action=\'btnCancel\'/></toolbar></ui>");
			this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar4")));
			this.toolbar4.Name = "toolbar4";
			this.toolbar4.ShowArrow = false;
			this.fixed3.Add(this.toolbar4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.toolbar4]));
			w2.X = 26;
			w2.Y = 19;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre de opción:");
			this.fixed3.Add(this.label4);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label4]));
			w3.X = 48;
			w3.Y = 124;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.txtOpc = new global::Gtk.Entry();
			this.txtOpc.CanFocus = true;
			this.txtOpc.Name = "txtOpc";
			this.txtOpc.IsEditable = true;
			this.txtOpc.InvisibleChar = '•';
			this.fixed3.Add(this.txtOpc);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txtOpc]));
			w4.X = 187;
			w4.Y = 117;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btnBack = new global::Gtk.Button();
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed3.Add(this.btnBack);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btnBack]));
			w5.X = 43;
			w5.Y = 245;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 434;
			this.DefaultHeight = 300;
			this.Show();
			this.btnSave.Activated += new global::System.EventHandler(this.OnBtnSaveActivated);
			this.btnBack.Clicked += new global::System.EventHandler(this.OnBtnBackClicked);
		}
	}
}
