
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0.UserRol
{
	public partial class frmModUserRol
	{
		public virtual void Build()
		{
			// Action group ScapProject0.UserRol.frmModUserRol
		}
	}
}
