
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0
{
	public partial class FrmLoginAdmin
	{
		private global::Gtk.Fixed fixed4;

		private global::Gtk.Label label4;

		private global::Gtk.ComboBox combobox4;

		private global::Gtk.Label label5;

		private global::Gtk.ComboBox combobox5;

		private global::Gtk.Label label6;

		private global::Gtk.ComboBox combobox6;

		private global::Gtk.Button button11;

		private global::Gtk.Button button12;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.FrmLoginAdmin
			this.Name = "ScapProject0.FrmLoginAdmin";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmLoginAdmin");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.FrmLoginAdmin.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("AREA:");
			this.fixed4.Add(this.label4);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label4]));
			w1.X = 88;
			w1.Y = 35;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.combobox4 = global::Gtk.ComboBox.NewText();
			this.combobox4.WidthRequest = 220;
			this.combobox4.HeightRequest = 25;
			this.combobox4.Name = "combobox4";
			this.fixed4.Add(this.combobox4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.combobox4]));
			w2.X = 88;
			w2.Y = 61;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("USUARIO:");
			this.fixed4.Add(this.label5);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label5]));
			w3.X = 88;
			w3.Y = 110;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.combobox5 = global::Gtk.ComboBox.NewText();
			this.combobox5.WidthRequest = 220;
			this.combobox5.HeightRequest = 25;
			this.combobox5.Name = "combobox5";
			this.fixed4.Add(this.combobox5);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.combobox5]));
			w4.X = 88;
			w4.Y = 138;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("PIN:");
			this.fixed4.Add(this.label6);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.label6]));
			w5.X = 88;
			w5.Y = 187;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.combobox6 = global::Gtk.ComboBox.NewText();
			this.combobox6.WidthRequest = 220;
			this.combobox6.HeightRequest = 25;
			this.combobox6.Name = "combobox6";
			this.fixed4.Add(this.combobox6);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.combobox6]));
			w6.X = 88;
			w6.Y = 215;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.button11 = new global::Gtk.Button();
			this.button11.WidthRequest = 119;
			this.button11.HeightRequest = 25;
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseUnderline = true;
			this.button11.Label = global::Mono.Unix.Catalog.GetString("SALIR");
			this.fixed4.Add(this.button11);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.button11]));
			w7.X = 44;
			w7.Y = 273;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.button12 = new global::Gtk.Button();
			this.button12.WidthRequest = 119;
			this.button12.HeightRequest = 25;
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			this.button12.Label = global::Mono.Unix.Catalog.GetString("INGRESAR");
			this.fixed4.Add(this.button12);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.button12]));
			w8.X = 235;
			w8.Y = 273;
			this.Add(this.fixed4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 337;
			this.Show();
			this.button12.Clicked += new global::System.EventHandler(this.OnButton12Clicked);
		}
	}
}
