
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0.AdminPswd
{
	public partial class FrmAddPswd
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action GuardarAction;

		private global::Gtk.Action CancelarAction;

		private global::Gtk.Fixed fixed5;

		private global::Gtk.Button btnBack;

		private global::Gtk.Toolbar toolbar6;

		private global::Gtk.Entry entUser;

		private global::Gtk.Entry entPIN;

		private global::Gtk.Entry entPIN2;

		private global::Gtk.Button btnPIN2;

		private global::Gtk.Entry entName;

		private global::Gtk.Entry entApellido;

		private global::Gtk.Entry entEmail;

		private global::Gtk.Button btnPIN;

		private global::Gtk.Label label7;

		private global::Gtk.Label label6;

		private global::Gtk.Label label5;

		private global::Gtk.Label label4;

		private global::Gtk.Label label3;

		private global::Gtk.Label label2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.AdminPswd.FrmAddPswd
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.GuardarAction = new global::Gtk.Action("GuardarAction", global::Mono.Unix.Catalog.GetString("  Guardar"), null, "save");
			this.GuardarAction.IsImportant = true;
			this.GuardarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Guardar");
			w1.Add(this.GuardarAction, null);
			this.CancelarAction = new global::Gtk.Action("CancelarAction", global::Mono.Unix.Catalog.GetString("  Cancelar"), null, "cancel");
			this.CancelarAction.IsImportant = true;
			this.CancelarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("  Cancelar");
			w1.Add(this.CancelarAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ScapProject0.AdminPswd.FrmAddPswd";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmAddPswd");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.AdminPswd.FrmAddPswd.Gtk.Container+ContainerChild
			this.fixed5 = new global::Gtk.Fixed();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.btnBack = new global::Gtk.Button();
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed5.Add(this.btnBack);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.btnBack]));
			w2.X = 62;
			w2.Y = 450;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar6\'><toolitem name=\'GuardarAction\' action=\'GuardarAction" +
					"\'/><toolitem name=\'CancelarAction\' action=\'CancelarAction\'/></toolbar></ui>");
			this.toolbar6 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar6")));
			this.toolbar6.Name = "toolbar6";
			this.toolbar6.ShowArrow = false;
			this.fixed5.Add(this.toolbar6);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.toolbar6]));
			w3.X = 20;
			w3.Y = 9;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entUser = new global::Gtk.Entry();
			this.entUser.CanFocus = true;
			this.entUser.Name = "entUser";
			this.entUser.IsEditable = true;
			this.entUser.InvisibleChar = '•';
			this.fixed5.Add(this.entUser);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entUser]));
			w4.X = 200;
			w4.Y = 290;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entPIN = new global::Gtk.Entry();
			this.entPIN.WidthRequest = 120;
			this.entPIN.CanFocus = true;
			this.entPIN.Name = "entPIN";
			this.entPIN.IsEditable = true;
			this.entPIN.MaxLength = 4;
			this.entPIN.Visibility = false;
			this.entPIN.InvisibleChar = '•';
			this.fixed5.Add(this.entPIN);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entPIN]));
			w5.X = 200;
			w5.Y = 340;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entPIN2 = new global::Gtk.Entry();
			this.entPIN2.WidthRequest = 120;
			this.entPIN2.CanFocus = true;
			this.entPIN2.Name = "entPIN2";
			this.entPIN2.IsEditable = true;
			this.entPIN2.MaxLength = 4;
			this.entPIN2.InvisibleChar = '•';
			this.fixed5.Add(this.entPIN2);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entPIN2]));
			w6.X = 200;
			w6.Y = 390;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.btnPIN2 = new global::Gtk.Button();
			this.btnPIN2.CanFocus = true;
			this.btnPIN2.Name = "btnPIN2";
			this.btnPIN2.UseUnderline = true;
			this.btnPIN2.Label = global::Mono.Unix.Catalog.GetString("Ver");
			this.fixed5.Add(this.btnPIN2);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.btnPIN2]));
			w7.X = 330;
			w7.Y = 390;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entName = new global::Gtk.Entry();
			this.entName.CanFocus = true;
			this.entName.Name = "entName";
			this.entName.IsEditable = true;
			this.entName.InvisibleChar = '•';
			this.fixed5.Add(this.entName);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entName]));
			w8.X = 200;
			w8.Y = 140;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entApellido = new global::Gtk.Entry();
			this.entApellido.CanFocus = true;
			this.entApellido.Name = "entApellido";
			this.entApellido.IsEditable = true;
			this.entApellido.InvisibleChar = '•';
			this.fixed5.Add(this.entApellido);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entApellido]));
			w9.X = 200;
			w9.Y = 190;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entEmail = new global::Gtk.Entry();
			this.entEmail.CanFocus = true;
			this.entEmail.Name = "entEmail";
			this.entEmail.IsEditable = true;
			this.entEmail.InvisibleChar = '•';
			this.fixed5.Add(this.entEmail);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entEmail]));
			w10.X = 200;
			w10.Y = 240;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.btnPIN = new global::Gtk.Button();
			this.btnPIN.CanFocus = true;
			this.btnPIN.Name = "btnPIN";
			this.btnPIN.UseUnderline = true;
			this.btnPIN.Label = global::Mono.Unix.Catalog.GetString("Ver");
			this.fixed5.Add(this.btnPIN);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.btnPIN]));
			w11.X = 330;
			w11.Y = 340;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Confirmar PIN:");
			this.fixed5.Add(this.label7);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label7]));
			w12.X = 69;
			w12.Y = 401;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("PIN:");
			this.fixed5.Add(this.label6);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label6]));
			w13.X = 139;
			w13.Y = 355;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("User:");
			this.fixed5.Add(this.label5);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label5]));
			w14.X = 137;
			w14.Y = 302;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Email:");
			this.fixed5.Add(this.label4);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label4]));
			w15.X = 136;
			w15.Y = 253;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Apellido:");
			this.fixed5.Add(this.label3);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label3]));
			w16.X = 116;
			w16.Y = 198;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
			this.fixed5.Add(this.label2);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label2]));
			w17.X = 117;
			w17.Y = 142;
			this.Add(this.fixed5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 528;
			this.DefaultHeight = 522;
			this.Show();
			this.GuardarAction.Activated += new global::System.EventHandler(this.OnGuardarActionActivated);
			this.CancelarAction.Activated += new global::System.EventHandler(this.OnCancelarActionActivated);
			this.btnBack.Clicked += new global::System.EventHandler(this.OnBtnBackClicked);
			this.btnPIN2.Pressed += new global::System.EventHandler(this.OnBtnPIN2Pressed);
			this.btnPIN2.Released += new global::System.EventHandler(this.OnBtnPIN2Released);
			this.btnPIN.Pressed += new global::System.EventHandler(this.OnBtnPINPressed);
			this.btnPIN.Released += new global::System.EventHandler(this.OnBtnPINReleased);
		}
	}
}
