
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0
{
	public partial class FrmMarcarES
	{
		private global::Gtk.Fixed fixed7;

		private global::Gtk.Button btnEntrada;

		private global::Gtk.Button btnSalida;

		private global::Gtk.Button button17;

		private global::Gtk.Label labelHora;

		private global::Gtk.Label labelBienvenida;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.FrmMarcarES
			this.Name = "ScapProject0.FrmMarcarES";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmMarcarES");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.FrmMarcarES.Gtk.Container+ContainerChild
			this.fixed7 = new global::Gtk.Fixed();
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.btnEntrada = new global::Gtk.Button();
			this.btnEntrada.WidthRequest = 125;
			this.btnEntrada.HeightRequest = 68;
			this.btnEntrada.CanFocus = true;
			this.btnEntrada.Name = "btnEntrada";
			this.btnEntrada.UseUnderline = true;
			this.btnEntrada.Label = global::Mono.Unix.Catalog.GetString("Entrada");
			this.fixed7.Add(this.btnEntrada);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.btnEntrada]));
			w1.X = 77;
			w1.Y = 200;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.btnSalida = new global::Gtk.Button();
			this.btnSalida.WidthRequest = 125;
			this.btnSalida.HeightRequest = 68;
			this.btnSalida.CanFocus = true;
			this.btnSalida.Name = "btnSalida";
			this.btnSalida.UseUnderline = true;
			this.btnSalida.Label = global::Mono.Unix.Catalog.GetString("Salida");
			this.fixed7.Add(this.btnSalida);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.btnSalida]));
			w2.X = 291;
			w2.Y = 200;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.button17 = new global::Gtk.Button();
			this.button17.WidthRequest = 119;
			this.button17.CanFocus = true;
			this.button17.Name = "button17";
			this.button17.UseUnderline = true;
			this.button17.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed7.Add(this.button17);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.button17]));
			w3.X = 28;
			w3.Y = 330;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.labelHora = new global::Gtk.Label();
			this.labelHora.WidthRequest = 240;
			this.labelHora.HeightRequest = 120;
			this.labelHora.Name = "labelHora";
			this.labelHora.LabelProp = global::Mono.Unix.Catalog.GetString("00:00:00");
			this.labelHora.Justify = ((global::Gtk.Justification)(2));
			this.fixed7.Add(this.labelHora);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.labelHora]));
			w4.X = 131;
			w4.Y = 65;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.labelBienvenida = new global::Gtk.Label();
			this.labelBienvenida.Name = "labelBienvenida";
			this.labelBienvenida.LabelProp = global::Mono.Unix.Catalog.GetString("Buen dia, Alejandra!");
			this.fixed7.Add(this.labelBienvenida);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.labelBienvenida]));
			w5.X = 23;
			w5.Y = 11;
			this.Add(this.fixed7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 499;
			this.DefaultHeight = 389;
			this.Show();
			this.btnEntrada.Clicked += new global::System.EventHandler(this.OnBtnEntradaClicked);
			this.btnSalida.Clicked += new global::System.EventHandler(this.OnBtnSalidaClicked);
		}
	}
}
