
// This file has been generated by the GUI designer. Do not modify.
namespace ScapProject0
{
	public partial class FrmMarcarES
	{
		private global::Gtk.Fixed fixed7;

		private global::Gtk.Label label10;

		private global::Gtk.Button button15;

		private global::Gtk.Button button16;

		private global::Gtk.Button button17;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ScapProject0.FrmMarcarES
			this.Name = "ScapProject0.FrmMarcarES";
			this.Title = global::Mono.Unix.Catalog.GetString("FrmMarcarES");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ScapProject0.FrmMarcarES.Gtk.Container+ContainerChild
			this.fixed7 = new global::Gtk.Fixed();
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("*Mensaje de bienvenida*");
			this.fixed7.Add(this.label10);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.label10]));
			w1.X = 5;
			w1.Y = 5;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.button15 = new global::Gtk.Button();
			this.button15.WidthRequest = 92;
			this.button15.HeightRequest = 48;
			this.button15.CanFocus = true;
			this.button15.Name = "button15";
			this.button15.UseUnderline = true;
			this.button15.Label = global::Mono.Unix.Catalog.GetString("ENTRADA");
			this.fixed7.Add(this.button15);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.button15]));
			w2.X = 105;
			w2.Y = 177;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.button16 = new global::Gtk.Button();
			this.button16.WidthRequest = 92;
			this.button16.HeightRequest = 48;
			this.button16.CanFocus = true;
			this.button16.Name = "button16";
			this.button16.UseUnderline = true;
			this.button16.Label = global::Mono.Unix.Catalog.GetString("SALIDA");
			this.fixed7.Add(this.button16);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.button16]));
			w3.X = 291;
			w3.Y = 177;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.button17 = new global::Gtk.Button();
			this.button17.WidthRequest = 119;
			this.button17.HeightRequest = 25;
			this.button17.CanFocus = true;
			this.button17.Name = "button17";
			this.button17.UseUnderline = true;
			this.button17.Label = global::Mono.Unix.Catalog.GetString("REGRESAR");
			this.fixed7.Add(this.button17);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.button17]));
			w4.X = 28;
			w4.Y = 321;
			this.Add(this.fixed7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 499;
			this.DefaultHeight = 369;
			this.Show();
			this.button17.Clicked += new global::System.EventHandler(this.OnButton17Clicked);
		}
	}
}
